### ISSUE TITLE
Touchups for Milestone 1 Features

### ISSUE THREAD

**Issue by ketamethane** [GenesisWCH/Genes#17]
For the Login and Sign up page, the following have to be done.

**Login**

- [ ] 1. Adding announcement message 
- [x] 2. Forgot password feature
- [x] 3. Continue as guest feature
- [x] 4. Screen layout adjustment

**Sign Up**

- [x] 1. Adding toasts for edge cases (e.g. email already in use, email needs to have an NUS email domain, strong password restrictions)
- [x] 2. Screen layout adjustments
